version: 1.0.{build}
build_script:
- ps: >-
    dotnet restore

    dotnet build -c Release .\src\csMACnz.EmbedRes\project.json

    #TODO: Test

    cd src\csMACnz.EmbedRes

    #TODO: Version

    dotnet version $env:APPVEYOR_BUILD_VERSION

    cd ..\..\

    dotnet pack -c Release -o . .\src\csMACnz.EmbedRes\project.json
artifacts:
- path: csMACnz.EmbedRes.*.nupkg
  name: nuget   