version: 2.0.{build}
build_script:
- ps: >-
    dotnet restore

    dotnet build -c Release csMACnz.EmbedRes.sln /property:VersionPrefix=$env:APPVEYOR_BUILD_VERSION

    #TODO Test
    
    #dotnet test -c Release .\test\csMACnz.FluentJsonBuilder.Tests\csMACnz.FluentJsonBuilder.Tests.csproj

    dotnet pack -c Release -o ${pwd} .\src\csMACnz.EmbedRes\csMACnz.EmbedRes.csproj /property:VersionPrefix=$env:APPVEYOR_BUILD_VERSION
test: off
artifacts:
- path: csMACnz.EmbedRes.*.nupkg
  name: nuget   